apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: employees
    component: frontend
spec:
  selector:
    matchLabels:
      app: employees
      component: frontend
replicas: 3
template:
  metadata:
    labels:
    app: employees
      component: frontend
spec:
  containers:
  - name: myapp
    image: 250220560712.dkr.ecr.us-east-1.amazonaws.com/webapp:v1.2
    env:
    - name: DBHOST
      value: mysql.webserver.svc.cluster.local  # Replace with the hostname of MySQL service
    - name: DBUSER
      value: root
    - name: DBPWD
      value: password 
    - name: DATABASE
      value: employees 
      
    ports:
    - containerPort: 8080
    
