apiVersion: v1
kind: Pod
metadata:
  labels:
    run: myapp
  name: myapp
spec:
  containers:
#  - image: my_app
  - image: 250220560712.dkr.ecr.us-east-1.amazonaws.com/webapp:v1.2
    name: myapp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always