apiVersion: v1
kind: Pod
metadata:
  labels:
    run: mysql
  name: mysql
  namespace: dbsql
spec:
  containers:
  - image: 250220560712.dkr.ecr.us-east-1.amazonaws.com/mysql:v1.1
    name: mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: "pass123" 
      - name: MYSQL_DATABASE
        value: employees
      - name: DBUSER
        value: root
    ports:
      - containerPort: 3306
        protocol: TCP
